name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH agent with the private key from GitHub Secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Deploy to EC2 using SSH
      - name: Deploy to EC2
        run: |
          # Connect to EC2 and deploy the app
          ssh -o StrictHostKeyChecking=accept-new ${EC2_USER}@${EC2_HOST} << 'EOF'
            # Navigate to the project directory
            cd /var/www/next-app || exit

            # Pull the latest code from GitHub
            git pull origin main

            # Install dependencies
            npm install

            # Build the application
            npm run build

            # Restart the application using pm2 or another process manager
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
          EOF





