name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/next-app
            echo "Current branch: $(git branch --show-current)"
            echo "Fetching latest changes..."
            git fetch --all
            echo "Resetting to origin/main..."
            git reset --hard origin/main
            echo "Cleaning up .next directory..."
            rm -rf .next
            echo "Installing dependencies..."
            npm install
            echo "Building the project..."
            npm run build
            echo "Restarting PM2 process..."
            pm2 restart nextjs-app
            echo "Deployment complete!"
