name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH agent with the private key from GitHub Secrets
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Deploy to EC2 using SSH
      - name: Deploy to EC2
        run: |
          ssh -v -o StrictHostKeyChecking=accept-new ${EC2_USER}@${EC2_HOST} "cd /var/www/next-app && git pull origin main && npm install && npm run build && pm2 restart nextjs-app || pm2 start npm --name 'nextjs-app' -- start"
